## 导入pyodbc作为连接数据库的设定
pandas底下有一个io.sql,里面有一个to_sql 如果先导入，後续使用旧可以不用加上io_sql

In [63]:
import pyodbc
import pandas as pd 
import pandas.io.sql

pyodbc 的连接方式为odbc 比较老旧的连接方式，因为我是连接本地数据库ms sql 
其他的方式可以参考学习资源
* [Connecting Python to Oracle, SQL Server, MySQL, and PostgreSQL]
  (https://towardsdatascience.com/connecting-python-to-oracle-sql-server-mysql-and-postgresql-ea1e4523b1e9)
  
* [【呕心总结】python如何与mysql实现交互及常用sql语句]
  (https://juejin.im/post/5d8e0f2af265da5b7c4515ec)
* [数据科学 | pandas数据导入与导出]
  (https://zhuanlan.zhihu.com/p/88653839)

In [62]:
conn = pyodbc.connect(
    'Driver={SQL Server Native Client 10.0};'
    'Server=.;'
    'Database=gshm_jx;'
    'Trusted_Connection=yes;'
)
#{SQL Server Native Client 10.0} => mssql2008

* 方法一：使用游标，读取的结果的tuple 
* 方法二： pd.read_sql(sql_query, con)
* 方法二： pandas.io..read_sql(sql_query, con)

In [20]:
cursor = conn.cursor()
cursor.execute('select * from jx_dept_code where (data_mont ='2002-04')')

# for row in cursor: print(row)
# conn.close()


resultList = []
for row in cursor:
    resultList.append(list(row))
df = pd.DataFrame(resultList)

In [24]:
df

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,2018-01,2021000AYP,陈秋彦,950000487,真空采血管（红色）,13,0.97,1.0,0.0,0.97,...,JC01,,1044,1146,JC01,,,0,None,16180628
1,2018-01,2029000GWE,韦连萍,2103C,X线计算机体层(CT)扫描(单次多层扫描)加收,15,18.00,1.0,0.0,18.00,...,JC02,,1094,1189,JC02,,,0,None,16180629
2,2018-01,2029000GWE,韦连萍,2103B,X线计算机体层(CT)扫描(三维重建)加收,15,57.00,1.0,0.0,57.00,...,JC02,,1094,1189,JC02,,,0,None,16180630
3,2018-01,2029000GWE,韦连萍,2103A,X线计算机体层(CT)扫描(使用螺旋扫描)加收,15,45.00,1.0,0.0,45.00,...,JC02,,1094,1189,JC02,,,0,None,16180631
4,2018-01,2029000GWE,韦连萍,210300001A,X线计算机体层(CT)平扫,15,97.00,1.0,0.0,97.00,...,JC02,,1094,1189,JC02,,,0,None,16180632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275056,2020-04,20300006WI,黄燕青,950012764,一次性使用高压造影注射器及附件,13,112.00,1.0,0.0,112.00,...,ZS24,,1179,1179,ZS24,,0,0,None,38622465
3275057,2020-04,20300006WI,黄燕青,950012764,一次性使用高压造影注射器及附件,13,112.00,-1.0,0.0,-112.00,...,ZS24,,1179,1179,ZS24,,0,0,None,38622466
3275058,2020-04,20270008AW,韦引尚,950012764,一次性使用高压造影注射器及附件,13,112.00,1.0,0.0,112.00,...,ZS24,,1179,1179,ZS24,,0,0,None,38622467
3275059,2020-04,2021000EJ6,兰火先,950012764,一次性使用高压造影注射器及附件,13,112.00,1.0,0.0,112.00,...,ZS24,,1179,1179,ZS24,,0,0,None,38622468
3275060,2020-04,20240003AY,韦金华,950012764,一次性使用高压造影注射器及附件,13,112.00,1.0,0.0,112.00,...,ZS24,,1179,1179,ZS24,,0,0,None,38622469

In [41]:
sql="""
select * from jx_dept_code where dept_code = 'BJK01'
"""
df_dept_code = pd.read_sql(sql, conn)

df_dept_code_2 = pandas.io.sql.read_sql(sql , conn )

# sql_mz_charge_code = """
# select * from jx_mz_charge_detail 
# """

# df_dept_code_3 = pandas.io.sql.read_sql(sql_mz_charge_code , conn )

In [42]:
df_dept_code_2

,dept_code,dept_name,stand_code,stand_name,py_code,d_code,branch_flag,flag,kind_flag,flag1,flag2,upd_user,upd_date
0,BJK01,保健科,0,保健科,BJK,,,,,2019-07,NO,mis,2019-09-19 18:40:25

# # 修改数据库资料
对於全表插入、覆盖、或者新储存数据没有的表
这部份需要导入 
`
from sqlalchemy import create_engine
`
因为sqlalchemy里面有sqlliet3 ()

In [52]:
# 键入新的表
import pandas as pd
import pymssql 
from sqlalchemy import create_engine
db = 'gshm_jx'
engine = create_engine('mssql+pymssql://sa:123456@localhost/%s?charset=utf8' % db , echo=False)

print(engine)

Engine(mssql+pymssql://sa:***@localhost/gshm_jx?charset=utf8)

In [56]:
name = 'jx_dept_code_A'

pd.io.sql.to_sql(df_dept_code_2 ,name ,con = engine,if_exists='append',index=False)

df_dept_code_2.to_sql(name , engine,if_exists='append',index=False)

# if_exists= 'fail' ，如果数据库里面有表，则不会有任何改变
# 如果数据库里面有表,append 追加在表格後面，
# replce ，会覆盖同一个表名的数据